apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 436112110102.dkr.ecr.eu-west-2.amazonaws.com/lbg-pg-repo:nginx
        ports:
        - containerPort: 80
          name: http
        
---
kind: Service            
apiVersion: v1            
metadata:                 
  name: nginx-service     
spec:                     
  selector:               
    app: nginx            
  ports:                 
  - protocol: TCP         
    targetPort: 80      
    port: 80              
    name: http            
  type: LoadBalancer      