apiVersion: apps/v1
kind: Service            
apiVersion: v1            
metadata:                 
  name: uitest-service     
spec:                     
  selector:               
    app: ui-test            
  ports:                 
  - protocol: TCP         
    targetPort: 3000      
    port: 3000              
    name: http            
  type: LoadBalancer